export const Cardata = [
  {
    id: 1,
    Carname: "GMC Yukon XL ",
    Model: "2018",
    image: "/carimages/GMCYoukon2012.png",
    perhourPrice: 60,
    perKiloPrice: 80,
    totalseat: 6,
    isWifi: true,
    Luggage: 6,
  },
  {
    id: 2,
    Carname: "Jeep Grand Cherokee",
    Model: "2017",
    image: "/carimages/JeepGrandCherokee.png",
    perhourPrice: 80,
    perKiloPrice: 50,
    totalseat: 5,
    isWifi: true,
    Luggage: 5,
  },
  {
    id: 3,
    Carname: "Toyota Land Cruiser Prado",
    Model: "2017",
    image: "/carimages/ToyotaLandCruiserPrado.png",
    perhourPrice: 80,
    perKiloPrice: 50,
    totalseat: 5,
    isWifi: true,
    Luggage: 5,
  },
  {
    id: 4,
    Carname: "GMC Yukon XL 2012 ",
    Model: "2012",
    image: "/carimages/GMCYoukon2012.png",
    perhourPrice: 60,
    perKiloPrice: 80,
    totalseat: 6,
    isWifi: true,
    Luggage: 6,
  },
];
