export const Cardata = [
  {
    id: 1,
    Carname: "CHEVROLET SUBURBAN SUV ",
    Model: "2024",
    image: "/carimages/2024-CHEVROLET-SUBURBAN-SUV.png",
    perhourPrice: 79,
    perMilePrice: 2.50,
    Luggage: 4,
    totalseat: 5,
    passenger: 5,
    isWifi: true,
    childSeat: true
  },
  {
    id: 2,
    Carname: "GMC Yukon",
    Model: "2024",
    image: "/carimages/2024_GMC_Yukon.png",
    perhourPrice: 79,
    perMilePrice: 2.25,
    totalseat: 5,
    passenger: 5,
    Luggage: 5,
    isWifi: true,
    childSeat: true,
  },
  {
    id: 3,
    Carname: "Cadillac-Escalade",
    Model: "2024",
    image: "/carimages/2024-cadillac-escalade-esv.png",
    perhourPrice: 85,
    perMilePrice: 2.75,
    totalseat: 5,
    passenger: 5,
    Luggage: 4,
    isWifi: true,
    childSeat: true,
  },
  {
    id: 4,
    Carname: "Lincoln MKT ",
    Model: "2018",
    image: "/carimages/LINCOLN-MKT.png",
    perhourPrice: 75,
    perMilePrice: 2.25,
    totalseat: 4,
    passenger: 4,
    Luggage: 4,
    isWifi: true,
    childSeat: true,
  },
  {
    id: 5,
    Carname: "Mercedes-S-Class ",
    Model: "S-350",
    image: "/carimages/mercedes-s-class-s-350.png",
    perhourPrice: 79,
    perMilePrice: 2.50,
    totalseat: 3,
    passenger: 3,
    Luggage: 3,
    isWifi: true,
    childSeat: true,
  },
];
