export const Cardata = [
  {
    id: 1,
    Carname: "GMC Yukon XL OLD ",
    Model: "2018",
    image: "/carimages/GMCYoukon2012.png",
    perhourPrice: 60,
    perMilePrice: 2.25,
    Luggage: 6,
    totalseat: 6,
    passenger: 6,
    isWifi: true,
    childSeat: false
  },
  {
    id: 2,
    Carname: "Jeep Grand Cherokee",
    Model: "2017",
    image: "/carimages/JeepGrandCherokee.png",
    perhourPrice: 80,
    perMilePrice: 2.25,
    totalseat: 5,
    isWifi: true,
    Luggage: 5,
    childSeat: true,
    passenger: 5,
  },
  {
    id: 3,
    Carname: "Land Cruiser Prado",
    Model: "2017",
    image: "/carimages/ToyotaLandCruiserPrado.png",
    perhourPrice: 80,
    perMilePrice: 2.25,
    totalseat: 8,
    isWifi: true,
    Luggage: 5,
    childSeat: false,
    passenger: 8,
  },
  {
    id: 4,
    Carname: "GMC Yukon XL ",
    Model: "2012",
    image: "/carimages/GMCYoukon2012.png",
    perhourPrice: 60,
    perMilePrice: 2.25,
    totalseat: 4,
    isWifi: true,
    Luggage: 6,
    childSeat: true,
    passenger: 4,
  },
];
