export const CITY_TO_CITY_INPUT_CHANGE = "CITY_TO_CITY_INPUT_CHANGE";
export const CITY_TO_CITY_STEP_INCREMENT_DECREMENT = "CITY_TO_CITY_STEP_INCREMENT_DECREMENT"
export const SELECTED_CAR_DATA = "SELECTED_CAR_DATA"
